In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])


In [3]:
print(a+b)

[ 8 10 12 14 16 18]


In [7]:
# creating 3D array

a3 = np.array([[[1,2],[3,4]],[[4,5],[5,6]]])
print(a3)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]
