In [11]:
import numpy as np

In [12]:
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])


In [13]:
print(a+b)

[ 8 10 12 14 16 18]


In [14]:
# creating 3D array

a3 = np.array([[[1,2],[3,4]],[[4,5],[5,6]]])
print(a3)

[[[1 2]
  [3 4]]

 [[4 5]
  [5 6]]]


In [18]:
# random array 
np.random.randint(1,25, size=(2,3))

array([[ 8,  9, 16],
       [ 5, 14, 14]], dtype=int32)

In [19]:
a = np.array([[1,2,5],
             [1,8,9],
             [4,8,6]])

b = np.array([[5,5,8],
              [4,6,9],
              [7,9,3]])

print(a)
print(b)

[[1 2 5]
 [1 8 9]
 [4 8 6]]
[[5 5 8]
 [4 6 9]
 [7 9 3]]


In [ ]:
# muliplication inverse matrix
print(a@b)
np.dot(a,b)

[[ 48  62  41]
 [100 134 107]
 [ 94 122 122]]


array([[ 48,  62,  41],
       [100, 134, 107],
       [ 94, 122, 122]])

In [22]:
a.prod() # prroduct of all elements in matrix or array

np.int64(138240)

In [23]:
b.mean()

np.float64(6.222222222222222)

In [24]:
a.mean(axis=0)

array([2.        , 6.        , 6.66666667])

In [25]:
print(a.sum())
print(a.std())
print(a.var())

44
2.9228769862146455
8.543209876543209


In [ ]:
a = np.array([4,5,6,8,4,9])

print(np.percentile(a,25)) # 1st quartile
print(np.percentile(a,50)) # median 
print(np.percentile(a,75)) # 3rd quartile

4.25
5.5
7.5


In [28]:
c = np.random.randint(11,100, size=(4,4))
print(c)

[[82 73 63 40]
 [34 92 40 56]
 [54 32 79 45]
 [59 71 88 76]]


In [30]:
print(c.reshape(2,8)) # reshaping into "2X8"
print(c.reshape(8,2))

[[82 73 63 40 34 92 40 56]
 [54 32 79 45 59 71 88 76]]
[[82 73]
 [63 40]
 [34 92]
 [40 56]
 [54 32]
 [79 45]
 [59 71]
 [88 76]]


In [32]:
arr = np.random.randint(1,40, (4,4))
arr

array([[14, 20, 21, 32],
       [11, 38,  2, 32],
       [39, 22, 14, 23],
       [22, 17, 11, 12]], dtype=int32)

In [ ]:
print(arr[0]) # print first row
print(arr[0,1]) # print frist row's 1 elements
print(arr[-1]) # print last row


[14 20 21 32]
20
[22 17 11 12]
[[14 20 21 32]
 [11 38  2 32]
 [39 22 14 23]]


In [40]:
print(arr[:3]) # slicing in matrix 
print(arr[1:])

[[14 20 21 32]
 [11 38  2 32]
 [39 22 14 23]]
[[11 38  2 32]
 [39 22 14 23]
 [22 17 11 12]]
